// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdmfhzefrfldfooglrwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkbWZoemVmcmZsZGZvb2dscndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODc0MDIsImV4cCI6MjA2ODA2MzQwMn0.0NTGWgBrjDvhMOmrqO1BNago9xLv61d2G7uGNbi3_ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});